### ISSUE TITLE
add special commit message strings to clear and skip cache

### ISSUE THREAD

**Issue by mvdan** [drone-plugins/drone-volume-cache#13]
We switched over from a third-party volume-cache plugin, which had support for clearing and skipping the cache like that:

https://github.com/Drillster/drone-volume-cache/blob/master/DOCS.md#clearing-cache

This is useful, because anyone who can start CI jobs by pushing to a branch can perform these actions. Otherwise, it's restricted to those who can ssh into the host machine and delete the tar files.

Was this left out on purpose? I hope not :)

**Comment by tboerger** [comment]
This could be added, but this doesn't work all the time. It only works if the last commit includes `[NO CACHE]` or `[CLEAR CACHE]` because other commit messages are never sent to those plugins.

**Comment by mvdan** [comment]
That seems fine, as long as it's properly documented.

**Comment by tboerger** [comment]
Feel free to prepare a PR ;)

**Comment by mvdan** [comment]
We ended up rolling our own caching via volumes years ago, and I no longer use Drone myself, so I think this issue can be closed. If someone else is inerested, they can always raise another issue or PR.
