### ISSUE TITLE
os.MkdirAll before creating archive file

### ISSUE THREAD

**Issue by bradrydzewski** [drone-plugins/drone-volume-cache#2]
Otherwise the code will deadlock and panic

**Comment by bugbuilder** [comment]
I think that this it could be managed by drone-cache-lib I made a [PR](https://github.com/drone/drone-cache-lib/pull/8)

**Comment by tboerger** [comment]
Solved via 2c3b7a79637dbcbda46144e9c31a2a80fea990a4
